/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.codetastrophe.cellfinder;

public final class R {
    public static final class array {
        public static final int pref_auto_center_options=0x7f050000;
        public static final int pref_coord_fmt_options=0x7f050001;
        public static final int pref_dist_unit_options=0x7f050002;
        public static final int prof_location_refresh_options=0x7f050003;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon_48x48=0x7f020000;
        public static final int reticle=0x7f020001;
        public static final int star_small=0x7f020002;
    }
    public static final class id {
        public static final int cell_info_view=0x7f070002;
        public static final int full_view=0x7f070001;
        public static final int layout_zoom=0x7f07000e;
        public static final int map_view=0x7f07000d;
        public static final int tv_about=0x7f070000;
        public static final int tv_cell_bearing=0x7f070007;
        public static final int tv_cell_cid_lac=0x7f070005;
        public static final int tv_cell_direction=0x7f070008;
        public static final int tv_location_coarse=0x7f07000a;
        public static final int tv_location_coarse_name=0x7f070009;
        public static final int tv_location_fine=0x7f07000c;
        public static final int tv_location_fine_name=0x7f07000b;
        public static final int tv_oper_num=0x7f070004;
        public static final int tv_oper_text=0x7f070003;
        public static final int tv_signal_str=0x7f070006;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int about_text=0x7f060051;
        public static final int about_title=0x7f06004f;
        public static final int about_title_fmt=0x7f060050;
        public static final int app_name=0x7f060000;
        public static final int app_package=0x7f060001;
        public static final int bearing_fmt=0x7f060015;
        public static final int bold_fmt=0x7f060020;
        public static final int dd_fmt=0x7f06001c;
        public static final int ddm_fmt=0x7f06001a;
        public static final int ddms_fmt=0x7f06001b;
        public static final int deg_fmt=0x7f06001f;
        public static final int distance_fmt_feet=0x7f060018;
        public static final int distance_fmt_meters=0x7f060016;
        public static final int distance_fmt_miles=0x7f060017;
        public static final int italics_fmt=0x7f060021;
        public static final int menu_title_about=0x7f060025;
        public static final int menu_title_settings=0x7f060024;
        public static final int min_fmt=0x7f06001d;
        public static final int operinfo_fmt=0x7f060013;
        public static final int opernum_fmt=0x7f060014;
        public static final int perf_summary_auto_zoom_off=0x7f060028;
        public static final int perf_summary_auto_zoom_on=0x7f060027;
        public static final int perf_summary_compass_off=0x7f06002e;
        public static final int perf_summary_compass_on=0x7f06002d;
        public static final int perf_summary_satellite_off=0x7f06002b;
        public static final int perf_summary_satellite_on=0x7f06002a;
        public static final int pref_center_option_gps=0x7f060048;
        public static final int pref_center_option_midpoint=0x7f06004a;
        public static final int pref_center_option_network=0x7f060049;
        public static final int pref_center_option_none=0x7f06004b;
        public static final int pref_summary_show_cell_data_off=0x7f06004e;
        public static final int pref_summary_show_cell_data_on=0x7f06004d;
        public static final int pref_title_auto_center=0x7f060047;
        public static final int pref_title_auto_zoom=0x7f060026;
        public static final int pref_title_compass=0x7f06002c;
        public static final int pref_title_coord_fmt=0x7f060033;
        public static final int pref_title_dist_unit=0x7f06002f;
        public static final int pref_title_location_refresh=0x7f060038;
        public static final int pref_title_satellite=0x7f060029;
        public static final int pref_title_show_cell_data=0x7f06004c;
        public static final int pref_value_coord_fmt_dd=0x7f060034;
        public static final int pref_value_coord_fmt_ddm=0x7f060035;
        public static final int pref_value_coord_fmt_ddms=0x7f060036;
        public static final int pref_value_coord_fmt_mgrs=0x7f060037;
        public static final int pref_value_dist_unit_feet=0x7f060031;
        public static final int pref_value_dist_unit_meters=0x7f060032;
        public static final int pref_value_dist_unit_miles=0x7f060030;
        public static final int pref_value_location_refresh_0=0x7f060039;
        public static final int pref_value_location_refresh_1=0x7f06003a;
        public static final int pref_value_location_refresh_10=0x7f06003f;
        public static final int pref_value_location_refresh_120=0x7f060046;
        public static final int pref_value_location_refresh_15=0x7f060040;
        public static final int pref_value_location_refresh_2=0x7f06003b;
        public static final int pref_value_location_refresh_20=0x7f060041;
        public static final int pref_value_location_refresh_3=0x7f06003c;
        public static final int pref_value_location_refresh_30=0x7f060042;
        public static final int pref_value_location_refresh_4=0x7f06003d;
        public static final int pref_value_location_refresh_45=0x7f060043;
        public static final int pref_value_location_refresh_5=0x7f06003e;
        public static final int pref_value_location_refresh_60=0x7f060044;
        public static final int pref_value_location_refresh_90=0x7f060045;
        public static final int provider_coarse=0x7f060007;
        public static final int provider_coarse_error=0x7f060002;
        public static final int provider_disabled=0x7f06000b;
        public static final int provider_fine=0x7f060008;
        public static final int provider_fine_error=0x7f060003;
        public static final int provider_gps=0x7f06000a;
        public static final int provider_network=0x7f060009;
        public static final int provider_out_of_service=0x7f06000d;
        public static final int provider_temporarily_unavailable=0x7f06000e;
        public static final int provider_waiting=0x7f06000c;
        public static final int provider_warning=0x7f060004;
        public static final int sec_fmt=0x7f06001e;
        public static final int service_error_no_service=0x7f060005;
        public static final int service_error_phone_off=0x7f060006;
        public static final int service_state_noservice=0x7f060023;
        public static final int service_state_poweroff=0x7f060022;
        public static final int signal_fmt=0x7f060019;
        public static final int tvcellinfo_fmt=0x7f060012;
        public static final int tvlocation_coarse_fmt=0x7f060010;
        public static final int tvlocation_fine_fmt=0x7f060011;
        public static final int unknown=0x7f06000f;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
